module.exports.bans = [
    'Aegislash',
    'Arceus',
    'Blaziken',
    'Blaziken-Mega',
    'Darkrai',
    'Deoxys-Attack',
	'Deoxys-Defense',
    'Deoxys-Normal',
	'Deoxys-Speed',
    'Dialga',
    'Genesect',
    'Genesect-Burn',
    'Genesect-Chill',
    'Genesect-Douse',
    'Genesect-Shock',
    'Gengar-Mega',
    'Giratina',
    'Giratina-Origin',
	'Greninja',
	'Greninja-Ash',
    'Groudon',
    'Groudon-Primal',
    'Ho-Oh',
	'Kangaskhan-Mega',
    'Kyogre',
    'Kyogre-Primal',
    'Kyurem-White',
	//'Landorus',
    'Lucario-Mega',
    'Lugia',
    'Lunala',
	'Magearna',
	'Magearna-Original',
    'Marshadow',
	'Metagross-Mega',
	'Mawile-Mega',
    'Mewtwo',
    'Mewtwo-Mega-X',
    'Mewtwo-Mega-Y',
    'Naganadel',
    'Necrozma-Dawn-Wings',
    'Necrozma-Dusk-Megaane',
    'Necrozma-Ultra',
    'Pheromosa',
    'Palkia',
    'Rayquaza',
    'Rayquaza-Mega',
    'Reshiram',
    'Solgaleo',
    'Shaymin-Sky',
    'Salamence-Mega',
	//'Tapu Lele',
    'Xerneas',
    'Yveltal',
    'Zekrom',
    'Zygarde-Complete',
];

module.exports.tiers = [
    [100, [
		'Altaria-Mega,'
		'Charizard-Mega-X,'
		'Clefable,'
		'Kyurem-Black,'
		'Landorus-Therian,'
		'Lopunny-Mega,'
		'Mew,'
		'Necrozma,'
    ]],
	[95, [
		'Alakazam-Mega,'
		'Blacephalon,'
		'Celesteela,'
		'Charizard-Mega-Y,'
		'Diancie-Mega,'
		'Hoopa-Unbound,'
		'Jirachi,'
		'Kartana,'
		'Latias-Mega,'
		'Latios-Mega,'
		'Manaphy,'
		'Tapu Bulu,'
		'Tapu Koko,'
		'Venusaur-Mega,'
		'Victini,'
		'Zeraora,'
    ]],
	[90, [
		'Dragonite,'
		'Excadrill,'
		'Garchomp,'
		'Garchomp-Mega,'
		'Gardevoir-Mega,'
		'Heatran,'
		'Latias,'
		'Latios,'
		'Medicham-Mega,'
		'Pinsir-Mega,'
		'Scizor-Mega,'
		'Tornadus-Therian,'
		'Toxapex,'
		'Tyranitar-Mega,'
		'Volcarona,'
		'Zygarde,'
    ]],
	[80, [
		'Azumarill,'
		'Beedrill-Mega,'
		'Blissey,'
		'Chansey,'
		'Ferrothorn,'
		'Gallade-Mega,'
		'Gyarados-Mega,'
		'Heracross-Mega,'
		'Infernape,'
		'Keldeo,'
		'Manectric-Mega,'
		'Rotom-Wash,'
		'Sableye-Mega,'
		'Salamence,'
		'Sharpedo-Mega,'
		'Slowbro-Mega,'
		'Tangrowth,'
		'Terrakion,'
		'Thundurus,'
		'Thundurus-Therian,'
		'Weavile,'
		'Zapdos,'
    ]],
	[75, [
		'Absol-Mega,'
		'Alakazam,'
		'Bisharp,'
		'Buzzwole,'
		'Chandelure,'
		'Gengar,'
		'Gliscor,'
		'Gyarados,'
		'Hawlucha,'
		'Hippowdon,'
		'Hydreigon,'
		'Mamoswine,'
		'Mimikyu,'
		'Mimikyu-Totem',
		'Nihilego,'
		'Reuniclus,'
		'Scizor,'
		'Serperior,'
		'Silvally,'
		'Skarmory,'
		'Slowbro,'
		'Swampert-Mega,'
		'Tapu Fini,'
		'Tyranitar,'
		'Xurkitree,'
    ]],
	[70, [
		'Azelf,'
		'Breloom,'
		'Celebi,'
		'Cloyster,'
		'Conkeldurr,'
		'Darmanitan,'
		'Diggersby,'
		'Dugtrio,'
		'Haxorus,'
		'Klefki,'
		'Kyurem,'
		'Magnezone,'
		'Mandibuzz,'
		'Muk-Alola,'
		'Ninetales-Alola,'
		'Porygon2,'
		'Raikou,'
		'Shaymin,'
		'Slowking,'
		'Starmie,'
		'Suicune,'
		'Sylveon,'
		'Togekiss,'
		'Volcanion,'
    ]],
	[60, [
		'Aerodactyl-Mega,'
		'Aggron-Mega,'
		'Alomomola,'
		'Amoonguss,'
		'Araquanid,'
		'Arcanine,'
		'Cobalion,'
		'Cresselia,'
		'Escavalier,'
		'Espeon,'
		'Feraligatr,'
		'Galvantula,'
		'Kingdra,'
		'Kommo-o,'
		'Kommo-o-Totem,'
		'Krookodile,'
		'Lucario,'
		'Marowak-Alola,'
		'Marowak-Alola-Totem,'
		'Metagross,'
		'Nidoking,'
		'Nidoqueen,'
		'Pelipper,'
		'Porygon-Z,'
		'Primarina,'
		'Rotom-Heat,'
		'Sceptile-Mega,'
		'Scolipede,'
		'Staraptor,'
		'Umbreon,'
		'Jolteon,'
		'Pidgeot-Mega,'
		'Roserade,'
		'Stakataka,'
		'Whimsicott,'
    ]],
	[55, [
		'Blastoise-Mega,'
		'Bronzong,'
		'Crawdaunt,'
		'Crobat,'
		'Ditto,'
		'Donphan,'
		'Doublade,'
		'Dragalge,'
		'Emboar,'
		'Empoleon,'
		'Entei,'
		'Floette-Eternal,'
		'Flygon,'
		'Gligar,'
		'Goodra,'
		'Heracross,'
		'Houndoom-Mega,'
		'Lycanroc-Dusk,'
		'Mienshao,'
		'Milotic,'
		'Registeel,'
		'Rotom-Mow,'
		'Sharpedo,'
		'Snorlax,'
		'Swampert,'
		'Tentacruel,'
		'Tornadus,'
		'Tyrantrum,'
		'Vaporeon,'
		'Virizion,'
		'Zygarde-10%,'
    ]],
	[50, [
		'Chesnaught,'
		'Decidueye,'
		'Delphox,'
		'Dhelmise,'
		'Florges,'
		'Hitmontop,'
		'Honchkrow,'
		'Hoopa,'
		'Machamp,'
		'Minior,'
		'Omastar,'
		'Regirock,'
		'Rhyperior,'
		'Seismitoad,'
		'Slurpuff,'
		'Steelix-Mega,'
		'Talonflame,'
		'Durant,'
    ]],
	[40, [
		'Ampharos-Mega,'
		'Blastoise,'
		'Braviary,'
		'Drapion,'
		'Druddigon,'
		'Eelektross,'
		'Electivire,'
		'Forretress,'
		'Gardevoir,'
		'Gastrodon,'
		'Gigalith,'
		'Granbull,'
		'Heliolisk,'
		'Houndoom,'
		'Jellicent,'
		'Ludicolo,'
		'Magneton,'
		'Mantine,'
		'Meloetta,'
		'Mesprit,'
		'Miltank,'
		'Mismagius,'
		'Ninetales,'
		'Noivern,'
		'Politoed,'
		'Quagsire,'
		'Raichu-Alola,'
		'Salazzle,'
		'Salazzle-Totem,'
		'Scrafty,'
		'Sigilyph,'
		'Smeargle,'
		'Swellow,'
		'Tsareena,'
		'Typhlosion,'
		'Uxie,'
		'Vanilluxe,'
		'Vikavolt,'
		'Vikavolt-Totem,'
		'Wishiwashi,'
		'Yanmega,'
		'Zoroark,'
    ]],
	[35, [
		'Abomasnow-Mega,'
		'Accelgor,'
		'Aerodactyl,'
		'Ambipom,'
		'Avalugg,'
		'Banette-Mega,'
		'Camerupt-Mega,'
		'Cinccino,'
		'Cofagrigus,'
		'Exploud,'
		'Gallade,'
		'Golisopod,'
		'Hariyama,'
		'Hitmonlee,'
		'Incineroar,'
		'Kabutops,'
		'Klinklang,'
		'Lanturn,'
		'Lycanroc,'
		'Magmortar,'
		'Malamar,'
		'Manectric,'
		'Meowstic,'
		'Pangoro,'
		'Persian-Alola,'
		'Piloswine,'
		'Pyroar,'
		'Qwilfish,'
		'Rampardos,'
		'Rhydon,'
		'Sableye,'
		'Samurott,'
		'Sandslash-Alola,'
		'Sawk,'
		'Sawsbuck,'
		'Sceptile,'
		'Shuckle,'
		'Spiritomb,'
		'Steelix,'
		'Stoutland,'
		'Togetic,'
		'Torkoal,'
		'Toxicroak,'
		'Trevenant,'
		'Type: Null,'
		'Venomoth,'
		'Venusaur,'
		'Weezing,'
		'Xatu,'
    ]],
	[30, [
		'Archeops',
		'Audino-Mega',
		'Aurorus',
		'Barbaracle',
		'Beartic',
		'Bewear',
		'Bouffalant',
		'Bruxish',
		'Clawitzer',
		'Cradily',
		'Cryogonal',
		'Dodrio',
		'Drampa',
		'Exeggutor',
		'Exeggutor-Alola',
		'Froslass',
		'Garbodor',
		'Glalie-Mega',
		'Golbat',
		'Golem',
		'Golurk',
		'Gorebyss',
		'Guzzlord',
		'Huntail',
		'Jynx',
		'Kecleon',
		'Kingler',
		'Leavanny',
		'Lilligant',
		'Linoone',
		'Medicham',
		'Moltres',
		'Mudsdale',
		'Muk',
		'Musharna',
		'Palossand',
		'Passimian',
		'Pinsir',
		'Primeape',
		'Raichu',
		'Regice',
		'Ribombee',
		'Ribombee-Totem',
		'Rotom-Frost',
		'Rotom-Fan',
		'Sandslash',
		'Slaking',
		'Sneasel',
		'Stunfisk',
		'Swoobat',
		'Tauros',
		'Torterra',
		'Toucannon',
		'Whiscash',
		'Ursaring',
		'Zangoose',
    ]],
	[20, [
		'Abomasnow',
		'Ariados',
		'Armaldo',
		'Aromatisse',
		'Cacturne',
		'Carracosta',
		'Charizard',
		'Chatot',
		'Clefairy',
		'Diancie',
		'Dugtrio-Alola',
		'Dusclops',
		'Electrode',
		'Floatzel',
		'Golem-Alola',
		'Gourgeist',
		'Jumpluff',
		'Kadabra',
		'Komala',
		'Lickilicky',
		'Liepard',
		'Lurantis',
		'Lurantis-Totem',
		'Luxray',
		'Marowak',
		'Masquerain',
		'Mawile',
		'Mr. Mime',
		'Murkrow',
		'Poliwrath',
		'Probopass',
		'Pyukumuku',
		'Regigigas',
		'Skuntank',
		'Tangela',
		'Togedemaru',
		'Togedemaru-Totem',
		'Turtonator',
		'Vileplume',
		'Vivillon',
    ]],
	[15, [
		'Altaria',
		'Ampharos',
		'Arbok',
		'Articuno',
		'Audino',
		'Basculin',
		'Bastiodon',
		'Beautifly',
		'Beheeyem',
		'Bibarel',
		'Butterfree',
		'Carbink',
		'Claydol',
		'Drifblim',
		'Dunsparce',
		'Dusknoir',
		'Gogoat',
		'Golduck',
		'Kangaskhan',
		'Leafeon',
		'Lopunny',
		'Lycanroc-Midnight',
		'Meowstic-F',
		'Mightyena',
		'Mothim',
		'Oricorio',
		'Pachirisu',
		'Phione',
		'Purugly',
		'Rapidash',
		'Raticate-Alola',
		'Raticate-Alola-Totem',
		'Scyther',
		'Seaking',
		'Shedinja',
		'Simipour',
		'Simisage',
		'Simisear',
		'Stantler',
		'Swanna',
		'Shiinotic',
		'Throh',
		'Tropius',
		'Victreebell',
		'Wailord',
		'Wigglytuff',
		'Zebstrika',
    ]],
	[10, [
		'Aron',
		'Bellossom',
		'Camerupt',
		'Carnivine',
		'Corsola',
		'Delcatty',
		'Delibird',
		'Dewgong',
		'Dustox',
		'Duosion',
		"Farfetch'd",
		'Fearow',
		'Ferroseed',
		'Furfrou',
		'Furret',
		'Glaceon',
		'Glalie',
		'Gothitelle',
	    //'Groudon-P', :eyes:
		'Haunter',
		'Heatmor',
		'Hypno',
		'Lairon',
		'Ledian',
		'Lumineon',
		'Lunatone',
		'Magcargo',
		'Magikarp',
		'Maractus',
		'Meganium',
		'Minun',
		'Noctowl',
		'Octillery',
		'Oranguru',
		'Parasect',
		'Pawniard',
		'Persian',
		'Pidgeot',
		'Plusle',
		'Raticate',
		'Relicanth',
		'Shiftry',
		'Solrock',
		'Spinda',
		'Sudowoodo',
		'Sunflora',
		'Sunkern',
		'Swalot',
		'Swinub',
		'Unfezant',
		'Vespiquen',
		'Volbeat',
		'Vulpix-Alola',
		'Walrein',
		'Wobbuffet',
		'Wormadam',
    ]],
]

module.exports.defCost = 10;
module.exports.maxPoints = 400;
module.exports.rosterPoints = 475;

const getCost = species => {
    for (const i of module.exports.tiers) {
        if (i[1].includes(species)) return i[0];
    }
    return module.exports.defCost;
};

module.exports.getCost = (template, item = {}) => {
    const megaEvolves = item.megaEvolves || false;

    if(getCost(template.species) < getCost(template.baseSpecies) && getCost(template.species) === module.exports.defCost && !megaEvolves) {
        return getCost(template.baseSpecies);
        //This won't work if a non-Mega form of a Pokémon that has a price is dropped to costing 25, but there are no cases of that currently//
    }
    else {
        return getCost(template.species);
    }
};

module.exports.getCostRaw = getCost;